version: '3.8'

services:
  airflow:
    build: .
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins

  druid:
    build: druid

  metabase:
    build: metabase
    volumes:
      - ./metabase:/metabase-data

  nginx:
    build: nginx
    volumes:
      - ./nginx/public:/usr/share/nginx/html
