version: '3.8'

volumes:
  airflow-logs: {}
  druid-segments: {}
  filesystem: {}
  postgres-data: {}

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

  airflow:
    depends_on:
      - postgres
      - druid
    environment:
      - PYTHONDONTWRITEBYTECODE=y
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=1
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=irn8s6ex88t9nDVzV9YlQQ9en112o9P5CEK8bGWJ8fE=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW_CONN_DRUID_INGEST=http://druid:8081?endpoint=druid%2Findexer%2Fv1%2Ftask
    volumes:
      - filesystem:/tmp/filesystem
      - airflow-logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: bash -c 'airflow initdb && { airflow scheduler & airflow webserver ; }'

  druid:
    depends_on:
      - postgres
    volumes:
      - druid-segments:/var/druid/segments
      - filesystem:/tmp/filesystem
    ports:
      - "8888:8888"

  metabase:
    depends_on:
      - druid
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "3000:3000"

  nginx:
    depends_on:
      - metabase
    ports:
      - "80:80"
