version: '3.7'

volumes:
  database: {}
  storage: {}
  filesystem: {}

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data/pgdata

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    restart: always
    depends_on:
      - postgres
      - druid
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - PYTHONDONTWRITEBYTECODE=y
      - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=1
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_CONN_DRUID_INGEST=http://druid:8081?endpoint=druid%2Findexer%2Fv1%2Ftask
    volumes:
      - filesystem:/tmp/filesystem
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  druid:
    build:
      context: ./druid
      args:
        DRUID_VERSION: 0.17.1
    depends_on:
      - postgres
    volumes:
      - storage:/var/druid/segments
      - filesystem:/tmp/filesystem

  metabase:
    image: metabase/metabase
    depends_on:
      - druid
    volumes:
      - ./metabase:/metabase-data
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      - MB_DB_FILE=/metabase-data/metabase.db

  nginx:
    build: ./nginx
    depends_on:
      - metabase
    ports:
      - "80:80"
