version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '3'
  driver: json-file

volumes:
  database: {}
  storage: {}
  filesystem: {}

services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data/pgdata
    logging: *default-logging

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    restart: always
    depends_on:
      - postgres
      - druid
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - PYTHONDONTWRITEBYTECODE=y
      - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=1
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_CONN_DRUID_INGEST=http://druid:8081?endpoint=druid%2Findexer%2Fv1%2Ftask
    volumes:
      - filesystem:/tmp/filesystem
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging: *default-logging

  druid:
    build:
      context: ./druid
      args:
        DRUID_VERSION: 0.17.1
    restart: always
    depends_on:
      - postgres
    volumes:
      - storage:/var/druid/segments
      - filesystem:/tmp/filesystem
    logging: *default-logging

  metabase:
    image: metabase/metabase
    restart: always
    depends_on:
      - druid
    volumes:
      - ./metabase:/metabase-data
    ports:
      - "3000:3000"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      - MB_DB_FILE=/metabase-data/metabase.db
    logging: *default-logging

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - metabase
    environment:
      - API_KEY=<signup at nginx amplify to get an api key>
      - AMPLIFY_IMAGENAME=coronavirus-dashboard
    ports:
      - "80:80"
      - "443:443"
    logging: *default-logging
