FROM nginx:1.19
ARG SSL_CERT
ARG SSL_CERT_KEY

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY public /usr/share/nginx/html

RUN mkdir /etc/nginx/certs \
  && echo $SSL_CERT > /etc/nginx/certs/fullchain.pem \
  && echo $SSL_CERT_KEY > /etc/nginx/certs/privkey.pem
