name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get shortsha
        id: vars
        run: echo ::set-output name=sha_short::$(git rev-parse --short ${{ github.sha }})
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Airflow
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alexnu/coronavirus-airflow:${{ steps.vars.outputs.sha_short }}
      - name: Publish Nginx
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: alexnu/coronavirus-nginx:${{ steps.vars.outputs.sha_short }}
      - name: Publish Druid
        uses: docker/build-push-action@v2
        with:
          context: ./druid
          file: ./druid/Dockerfile
          push: true
          tags: alexnu/coronavirus-druid:${{ steps.vars.outputs.sha_short }}
      - name: Publish Metabase
        uses: docker/build-push-action@v2
        with:
          context: ./metabase
          file: ./metabase/Dockerfile
          push: true
          tags: alexnu/coronavirus-metabase:${{ steps.vars.outputs.sha_short }}
